Attempt autoblack

diff --git a/.github/workflows/verify.yml b/.github/workflows/verify.yml
--- a/.github/workflows/verify.yml
+++ b/.github/workflows/verify.yml
@@ -64,11 +64,54 @@ jobs:
         . venv/bin/activate
         pre-commit install-hooks
 
+  black:
+    runs-on: ubuntu-latest
+    needs: prepare
+    steps:
+    - name: Check out committed code
+      uses: actions/checkout@v2
+    - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+      id: python
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ env.DEFAULT_PYTHON }}
+    - name: Pre-black
+      uses: psf/black@stable
+    - name: Restore base Python ${{ env.DEFAULT_PYTHON }} virtual environment
+      id: cache-venv
+      uses: actions/cache@v2
+      with:
+        path: venv
+        key: >-
+          ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{
+          steps.python.outputs.python-version }}-${{
+          hashFiles('requirements_test.txt') }}-${{
+          hashFiles('setup.py') }}
+    - name: Fail job if Python cache restore failed
+      if: steps.cache-venv.outputs.cache-hit != 'true'
+      run: |
+        echo "Failed to restore Python ${{ env.DEFAULT_PYTHON }} virtual environment from cache"
+        exit 1
+    - name: Install Black
+      run: pip install black
+    - name: Run black --check .
+      run: black --check .
+    - name: If needed, commit black changes to the pull request
+      if: failure()
+      run: |
+        black .
+        git config --global user.name 'autoblack'
+        git config --global user.email 'plugwise@users.noreply.github.com'
+        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
+        git checkout $GITHUB_HEAD_REF
+        git commit -am "fixup: Format Python code with Black"
+        git push
+
 
   commitcheck:
     runs-on: ubuntu-latest
     name: Check commit
-    needs: prepare
+    needs: black
     steps:
     - name: Check out committed code
       uses: actions/checkout@v2
