Restore github-testing

diff --git a/.github/workflows/verify.yml b/.github/workflows/verify.yml
--- a/.github/workflows/verify.yml
+++ b/.github/workflows/verify.yml
@@ -161,124 +161,125 @@ jobs:
           pre-commit run --show-diff-on-failure --color=always --all-files --hook-stage manual userdata
           pre-commit run --show-diff-on-failure --color=always --all-files --hook-stage manual yamllint
 
-#  prepare-test-cache:
-#    runs-on: ubuntu-latest
-#    name: Create pytest cache for Python ${{ matrix.python-version }}
-#    needs: commitcheck
-#    strategy:
-#      matrix:
-#        python-version: [3.8, 3.9]
-#    steps:
-#      - name: Check out committed code
-#        uses: actions/checkout@v2
-#      - name: Set up Python ${{ matrix.python-version }}
-#        id: python
-#        uses: actions/setup-python@v2
-#        with:
-#          python-version: ${{ matrix.python-version }}
-#      - name: Restore full Python ${{ matrix.python-version }} virtual environment
-#        id: cache-venv
-#        uses: actions/cache@v2
-#        with:
-#          path: venv
-#          key: >-
-#            ${{ env.CACHE_VERSION}}-${{ runner.os }}-venv-${{
-#            matrix.python-version }}-${{ hashFiles('requirements_test.txt')
-#            }}-${{ hashFiles('setup.py') }}
-#          restore-keys: |
-#            ${{ env.CACHE_VERSION}}-${{ runner.os }}-venv-${{ matrix.python-version }}-${{ hashFiles('requirements_test.txt') }}-${{ hashFiles('setup.py') }}
-#            ${{ env.CACHE_VERSION}}-${{ runner.os }}-venv-${{ matrix.python-version }}-${{ hashFiles('requirements_test.txt') }}
-#            ${{ env.CACHE_VERSION}}-${{ runner.os }}-venv-${{ matrix.python-version }}-
-#      - name: Create full Python ${{ matrix.python-version }} virtual environment
-#        if: steps.cache-venv.outputs.cache-hit != 'true'
-#        run: |
-#          python -m venv venv
-#          . venv/bin/activate
-#          pip install -U pip setuptools wheel
-#          pip install -e .
-#          pip install -r requirements_test.txt
+  prepare-test-cache:
+    runs-on: ubuntu-latest
+    name: Create pytest cache for Python ${{ matrix.python-version }}
+    needs: commitcheck
+    strategy:
+      matrix:
+        python-version: [3.8, 3.9]
+    steps:
+      - name: Check out committed code
+        uses: actions/checkout@v2
+      - name: Set up Python ${{ matrix.python-version }}
+        id: python
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Restore full Python ${{ matrix.python-version }} virtual environment
+        id: cache-venv
+        uses: actions/cache@v2
+        with:
+          path: venv
+          key: >-
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-venv-${{
+            matrix.python-version }}-${{ hashFiles('requirements_test.txt')
+            }}-${{ hashFiles('setup.py') }}
+          restore-keys: |
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-venv-${{ matrix.python-version }}-${{ hashFiles('requirements_test.txt') }}-${{ hashFiles('setup.py') }}
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-venv-${{ matrix.python-version }}-${{ hashFiles('requirements_test.txt') }}
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-venv-${{ matrix.python-version }}-
+      - name: Create full Python ${{ matrix.python-version }} virtual environment
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          python -m venv venv
+          . venv/bin/activate
+          pip install -U pip setuptools wheel
+          pip install -e .
+          pip install -r requirements_test.txt
 
-#  pytest:
-#    runs-on: ubuntu-latest
-#    name: Run pytest using Python ${{ matrix.python-version }}
-#    needs: prepare-test-cache
-#    strategy:
-#      matrix:
-#        python-version: [3.8, 3.9]
-#    steps:
-#      - name: Check out committed code
-#        uses: actions/checkout@v2
-#      - name: Set up Python ${{ matrix.python-version }}
-#        id: python
-#        uses: actions/setup-python@v2
-#        with:
-#          python-version: ${{ matrix.python-version }}
-#      - name: Restore full Python ${{ matrix.python-version }} virtual environment
-#        id: cache-venv
-#        uses: actions/cache@v2
-#        with:
-#          path: venv
-#          key: >-
-#            ${{ env.CACHE_VERSION}}-${{ runner.os }}-venv-${{
-#            matrix.python-version }}-${{ hashFiles('requirements_test.txt')
-#            }}-${{ hashFiles('setup.py') }}
-#      - name: Fail job if Python cache restore failed
-#        if: steps.cache-venv.outputs.cache-hit != 'true'
-#        run: |
-#          echo "Failed to restore Python virtual environment from cache"
-#          exit 1
-#      - name: Run all tests
-#        run: |
-#          . venv/bin/activate
-#          pytest --log-level info tests/*.py --cov='.'
-#      - name: Upload coverage artifact
-#        uses: actions/upload-artifact@v2.2.0
-#        with:
-#          name: coverage-${{ matrix.python-version }}
-#          path: .coverage
+  pytest:
+    runs-on: ubuntu-latest
+    name: Run pytest using Python ${{ matrix.python-version }}
+    needs: prepare-test-cache
+    strategy:
+      matrix:
+        python-version: [3.8, 3.9]
 
-#  coverage:
-#    name: Process test coverage
-#    runs-on: ubuntu-latest
-#    needs: pytest
-#    steps:
-#      - name: Check out code from GitHub
-#        uses: actions/checkout@v2
-#      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
-#        id: python
-#        uses: actions/setup-python@v2
-#        with:
-#          python-version: ${{ env.DEFAULT_PYTHON }}
-#      - name: Restore base Python ${{ env.DEFAULT_PYTHON }} virtual environment
-#        id: cache-venv
-#        uses: actions/cache@v2
-#        with:
-#          path: venv
-#          key: >-
-#            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{
-#            steps.python.outputs.python-version }}-${{
-#            hashFiles('requirements_test.txt') }}-${{
-#            hashFiles('setup.py') }}
-#      - name: Fail job if Python cache restore failed
-#        if: steps.cache-venv.outputs.cache-hit != 'true'
-#        run: |
-#          echo "Failed to restore Python virtual environment from cache"
-#          exit 1
-#      - name: Download all coverage artifacts
-#        uses: actions/download-artifact@v2
-#      - name: Combine coverage results
-#        run: |
-#          . venv/bin/activate
-#          coverage combine coverage*/.coverage*
-#          coverage report --fail-under=94
-#          coverage xml
-#      - name: Upload coverage to Codecov
-#        uses: codecov/codecov-action@v1
+    steps:
+      - name: Check out committed code
+        uses: actions/checkout@v2
+      - name: Set up Python ${{ matrix.python-version }}
+        id: python
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Restore full Python ${{ matrix.python-version }} virtual environment
+        id: cache-venv
+        uses: actions/cache@v2
+        with:
+          path: venv
+          key: >-
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-venv-${{
+            matrix.python-version }}-${{ hashFiles('requirements_test.txt')
+            }}-${{ hashFiles('setup.py') }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Run all tests
+        run: |
+          . venv/bin/activate
+          pytest --log-level info tests/*.py --cov='.'
+      - name: Upload coverage artifact
+        uses: actions/upload-artifact@v2.2.0
+        with:
+          name: coverage-${{ matrix.python-version }}
+          path: .coverage
+
+  coverage:
+    name: Process test coverage
+    runs-on: ubuntu-latest
+    needs: pytest
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2
+      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+        id: python
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+      - name: Restore base Python ${{ env.DEFAULT_PYTHON }} virtual environment
+        id: cache-venv
+        uses: actions/cache@v2
+        with:
+          path: venv
+          key: >-
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{
+            steps.python.outputs.python-version }}-${{
+            hashFiles('requirements_test.txt') }}-${{
+            hashFiles('setup.py') }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Download all coverage artifacts
+        uses: actions/download-artifact@v2
+      - name: Combine coverage results
+        run: |
+          . venv/bin/activate
+          coverage combine coverage*/.coverage*
+          coverage report --fail-under=94
+          coverage xml
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v1
 
   test-publishing:
     name: Build and publish Python 🐍 distributions 📦 to TestPyPI
     runs-on: ubuntu-latest
-    needs: commitcheck
+    needs: coverage
     steps:
       - name: Check out code from GitHub
         uses: actions/checkout@v2
@@ -312,35 +313,35 @@ jobs:
           repository_url: https://test.pypi.org/legacy/
           skip_existing: true
 
-#  complexity:
-#    name: Process test complexity
-#    runs-on: ubuntu-latest
-#    needs: coverage
-#    steps:
-#      - name: Check out code from GitHub
-#        uses: actions/checkout@v2
-#      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
-#        id: python
-#        uses: actions/setup-python@v2
-#        with:
-#          python-version: ${{ env.DEFAULT_PYTHON }}
-#      - name: Restore base Python ${{ env.DEFAULT_PYTHON }} virtual environment
-#        id: cache-venv
-#        uses: actions/cache@v2
-#        with:
-#          path: venv
-#          key: >-
-#            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{
-#            steps.python.outputs.python-version }}-${{
-#            hashFiles('requirements_test.txt') }}-${{
-#            hashFiles('setup.py') }}
-#      - name: Fail job if Python cache restore failed
-#        if: steps.cache-venv.outputs.cache-hit != 'true'
-#        run: |
-#          echo "Failed to restore Python virtual environment from cache"
-#          exit 1
-#      - name: Run complexity report (click to view details)
-#        run: |
-#          . venv/bin/activate
-#          echo "Showing complexity higher or equal to 'C'"
-#          radon cc plugwise/smile.py plugwise/helper.py tests/test_smile.py -s -nc --no-assert
+  complexity:
+    name: Process test complexity
+    runs-on: ubuntu-latest
+    needs: coverage
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2
+      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+        id: python
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+      - name: Restore base Python ${{ env.DEFAULT_PYTHON }} virtual environment
+        id: cache-venv
+        uses: actions/cache@v2
+        with:
+          path: venv
+          key: >-
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{
+            steps.python.outputs.python-version }}-${{
+            hashFiles('requirements_test.txt') }}-${{
+            hashFiles('setup.py') }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Run complexity report (click to view details)
+        run: |
+          . venv/bin/activate
+          echo "Showing complexity higher or equal to 'C'"
+          radon cc plugwise/smile.py plugwise/helper.py tests/test_smile.py -s -nc --no-assert
